AWSTemplateFormatVersion: 2010-09-09

Type: AWS::Lambda::Function
Properties: 
  Code: 
    Code
  Description: String
  Environment: 
    Environment
  FunctionName: String
  Handler: String
  KmsKeyArn: String
  Layers: 
    - String
  MemorySize: Integer
  ReservedConcurrentExecutions: Integer
  Role: String
  Runtime: String
  Tags: 
    - Tag
  Timeout: Integer
  TracingConfig: 
    TracingConfig
  VpcConfig: 
    VpcConfig